version: '3.7'

services:
  database:
    container_name: bitpanda-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    ports:
      - '3306:3306'
    volumes:
        - ./docker/database:/docker-entrypoint-initdb.d
